// Code generated by "stringer -type Orientation"; DO NOT EDIT.

package orientation

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TopLeft-1]
	_ = x[TopRight-2]
	_ = x[BottomRight-3]
	_ = x[BottomLeft-4]
	_ = x[LeftTop-5]
	_ = x[RightTop-6]
	_ = x[RightBottom-7]
	_ = x[LeftBottom-8]
}

const _Orientation_name = "TopLeftTopRightBottomRightBottomLeftLeftTopRightTopRightBottomLeftBottom"

var _Orientation_index = [...]uint8{0, 7, 15, 26, 36, 43, 51, 62, 72}

func (i Orientation) String() string {
	i -= 1
	if i < 0 || i >= Orientation(len(_Orientation_index)-1) {
		return "Orientation(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Orientation_name[_Orientation_index[i]:_Orientation_index[i+1]]
}
